### ISSUE TITLE
Доделать поддержку кастомных схем

### ISSUE THREAD

**Issue by Vittly** [bemhint/bemhint-deps-schema#12]
В версии 2.0 была предложена первая реализация кастомных схем. Цель - дать возможность разным проектам вводить свой код-стайл в deps.js-файлах.
Кажется, первая реализация была слишком наивной - мы просто подменяем дефолтную схему на другую, получается:
* валидатор депсов начинает валидировать все, что угодно (кастомная схема может быть вообще не про депсы)
* при описании код стайла придется написать нетривиальную схему, даже если хочется внести совсем небольшие изменения в обычные депсы

А давайте будет валидировать депсы сначала по стандарту, а потом допольнительно кастомной схемой? Тогда:
* кастомная схема может быть простой
* то, что прошло валидацию всегда будет депсом

**Comment by dima117** [comment]
Кажется, это можно сделать без изменения кода с помощью последовательного запуска валидации с разными схемами. Такой вариант подойдет?

**Comment by Vittly** [comment]
Ага, так и надо сделать

**Comment by dima117** [comment]
Закрываем issue?

--
С уважением,
Дмитрий Андриянов

-----Исходное сообщение-----
От: "Vitaly" <notifications@github.com>
Отправлено: ‎31.‎03.‎2017 8:47
Кому: "bemhint/bemhint-deps-schema" <bemhint-deps-schema@noreply.github.com>
Копия: "dima117" <dima117a@gmail.com>; "Comment" <comment@noreply.github.com>
Тема: Re: [bemhint/bemhint-deps-schema] Доделать поддержку кастомных схем (#12)

Ага, так и надо сделать

**Comment by Vittly** [comment]
не понял, почему? Сейчас, указывая кастомную схему - мы полностью переопределяем работу плагина. Надо убрать эту возможность и сделать, чтобы опция `schema` работала как-то не так - https://github.com/bemhint/bemhint-deps-schema/blob/master/lib/loader.js#L28

**Comment by dima117** [comment]
Нужная функциональность [добавлена](https://github.com/bemhint/bemhint/pull/85) в конфиг bemhint. Закрываю issue.
