### ISSUE TITLE
Задавать схему, используемую при валидации, настройкой плагина

### ISSUE THREAD

**Issue by Vittly** [bemhint/bemhint-deps-schema#4]
В разных проектах может быть свой код стайл, ограничивающий список используемых фич из `deps.js`. Например, такой список:
* не используем вложенные shouldDeps, mustDeps, noDeps
* не используем короткую запись shouldDeps в виде просто строки или массива строк

Для таких случаев хочется писать собственную схему (по аналогии с канонической из плагина) и подкладывать ее в плагин. В идеале иметь составные части канонической схемы (подсхемы) и строить свою схему из них

**Comment by dima117** [comment]
[готово](https://github.com/bemhint/bemhint-deps-schema#custom-schema)
