### ISSUE TITLE
Использовать cst-модуль для красивых сообщений об ошибках

### ISSUE THREAD

**Issue by Vittly** [bemhint/bemhint-deps-schema#8]
Хочется показывать "красивые" сообщения об ошибках, указывающие на номер строки/столбца (или, еще лучше, рисующие стрелочку), а не просто "у вас ошибка в `.shouldDeps[0].elems[5]`" .

Модуль [cst](https://www.npmjs.com/package/cst) должен помочь в этом.

**Comment by Vittly** [comment]
Покопался, лучше использовать `acorn` (на нем построен `espree`, используемый в `eslint`) - у него нет зависимостей и он возвращает AST

**Comment by dima117** [comment]
[готово](https://github.com/bemhint/bemhint-deps-schema#error-location)
